### ISSUE TITLE
A13 13.5 dont work

### ISSUE THREAD

**Issue by cilin1105** [Ic0nic0de/Ic0nic0de.github.io#6]
A13 with 13.5 wont work if plug charger and wont work most of the time. Just work when respring just for few minutes.

**Comment by cilin1105** [comment]
Tweak still working with enable button disable

**Comment by aes8789** [comment]
F

**Comment by Ic0nic0de** [comment]
13.5 works fine, i am aware of the Enabled issue which will be fixed shortly
